spring:
  datasource:
    url: jdbc:mysql://${EC2_DB}:3306/piece_of_cake
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: ${EC2_DB}
    port: 6379
    password: ${REDIS_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka/